# Generated by Django 5.2.6 on 2025-09-26 07:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Story',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('excerpt', models.TextField()),
                ('content', models.TextField()),
                ('image_url', models.URLField()),
                ('ai_hint', models.TextField()),
                ('related_product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='products.product')),
            ],
        ),
    ]
