# Generated by Django 5.2.6 on 2025-09-28 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_product_image_url'),
        ('stories', '0002_alter_story_image_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='related_product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stories', to='products.product'),
        ),
    ]
